### ISSUE TITLE
Calendars show 2015 instead of 2016

### ISSUE THREAD

**Issue by cthalin8** [printdotio/printio-ios-sdk#488]
When you edit images for each month of the calendar, they are for 2015 and should be for 2016. See attached screenshot...
![img_0030](https://cloud.githubusercontent.com/assets/15328807/11106556/d61832c0-888b-11e5-97a9-7108208c8394.PNG)

**Comment by perisicboro** [comment]
Fixed in new SDK version.

**Comment by cthalin8** [comment]
Can you let me know which version this is? We thought we had the latest version and it's not working.

**Comment by tobiasfrier** [comment]
@cthalin8 It is going out in our next release.

**Comment by cthalin8** [comment]
We have the latest release and the calendars still show "2015" instead of "2016"...
![img_5495](https://cloud.githubusercontent.com/assets/15328807/11547262/78b37734-9907-11e5-9b5e-aa9c6d6c67ed.PNG)

**Comment by tobiasfrier** [comment]
@cthalin8 
We are making a release tomorrow that will solve this problem. Thank you for you patience.

**Comment by perisicboro** [comment]
Our QA verified this.
